# let's see if comments work
branches:
  only:
    - master
language: ruby
rvm:
  - 1.9.3
env:
  global:
    - secure: "S3277NQOIHsgdDlm3Gruua5HpE3Pv7VDritkRu8u4cV6K0qpZ3Rv9e/HEgDb\nlBVeQqNFNsiWHYNIN+4dMTPswfGf/eXnDA594yIeg9aNoRGEHlM95ily1+hx\nBTOjShBeGoQMzQFEbHn6LuZeLGfMtmwZEEfZjwt5K8lo/UBoHJM="   
    - secure: "SX4PIvN9EtxuhsbVInC2/Ba5ECMqQUmiBB8I1N4m6MaU6kfol9JXrWhXRzEA\nTwgB2PqBQ/FMbu4EQeTjSudcbd0iu3mhG1eIfLpxHa1hkuK6HgnkYkk8wcDN\nFFasAMBPquMx20s26ZoVVYbVb+B7LdbqtRw4M7SmNYPn2nJ1OSY="
bundler_args: "--without development"
before_install:
  - gem install bundler --pre
script:
  - "RAILS_ENV=test bundle exec rake db:migrate --trace"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake"
before_script:
  - "cp config/database.travis.example.yml config/database.yml"
  - "cp config/application.example.yml config/application.yml"
  - "psql -c 'create database travis_test' -U postgres"