# let's see if comments work

language: ruby
rvm:
  - 1.9.3
bundler_args: "--without development"
before_install:
  - gem install bundler --pre
before_script:
  - "cp config/database.travis.example.yml config/database.yml"
  - "cp config/application.example.yml config/application.yml:"
